# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: WowOpenBox/BuildKit
          path: buildkit

      - name: Get and set the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${VERSION}
          if [ -z "${VERSION##*pre*}" ]; then
            echo ::set-output name=PRERELEASE::true
          else
            echo ::set-output name=PRERELEASE::false
          fi
          sed -i -e "s/^set vers .*$/set vers \"$VERSION\"/" WowOpenBox.tkapp
        shell: bash

      - name: Make the executable
        run: |
          cd buildkit
          cp ..\WowOpenBox.tkapp OpenMultiBoxing.vfs\app
          Add-Content -Path OpenMultiBoxing.vfs\tclkit.inf -Value "ProductVersion ""${{ steps.get_version.outputs.VERSION }}""" -PassThru
          tclkit\tclkit.exe sdx\sdx.kit wrap OpenMultiBoxing -runtime runtime.exe
          Rename-Item OpenMultiBoxing OpenMultiBoxing.exe
          .\upx.exe --ultra-brute --compress-resources=0 OpenMultiBoxing.exe


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: WowOpenBox / OpenMultiBoxing ${{ steps.get_version.outputs.VERSION }}
          draft: true
          prerelease: ${{ steps.get_version.outputs.PRERELEASE }}

      - name: Upload Binary
        id: upload-release-asset1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: .\buildkit\OpenMultiBoxing.exe
          asset_name: OpenMultiBoxing-${{ steps.get_version.outputs.VERSION }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Update Code
        id: upload-release-asset2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: WowOpenBox.tkapp
          asset_name: WowOpenBox-${{ steps.get_version.outputs.VERSION }}.tkapp
          asset_content_type: application/octet-stream

#      - uses: actions/upload-artifact@v2
#        with:
#          name: OpenMultiboxing-artifact
#          path: buildkit\OpenMultiBoxing.exe
