# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: WowOpenBox/BuildKit
          path: buildkit
        
      - name: Make the executable
        run: |
          cd buildkit
          mkdir OpenMultiBoxing.vfs\app
          cp ..\WowOpenBox.tkapp OpenMultiBoxing.vfs\app
          tclkit\tclkit.exe sdx\sdx.kit wrap OpenMultiBoxing -runtime runtime.exe
          rename OpenMultiBoxing OpenMultiBoxing.exe

      - uses: actions/upload-artifact@v2
        with:
          name: OpenMultiboxing-artifact
          path: buildkit\OpenMultiBoxing.exe
