# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: WowOpenBox/BuildKit
          path: buildkit
        
      - name: Make the executable
        run: |
          $version=(git.exe describe --tags --match 'v*').Trim()
          Add-Content -Path buildkit\OpenMultiBoxing.vfs\tclkit.inf -Value "ProductVersion ""$version""" -PassThru
          cd buildkit
          mkdir OpenMultiBoxing.vfs\app
          cp ..\WowOpenBox.tkapp OpenMultiBoxing.vfs\app
          tclkit\tclkit.exe sdx\sdx.kit wrap OpenMultiBoxing -runtime runtime.exe
          Rename-Item OpenMultiBoxing OpenMultiBoxing.exe
          .\upx.exe -q --ultra-brute --compress-resources=0 OpenMultiBoxing.exe

      - uses: actions/upload-artifact@v2
        with:
          name: OpenMultiboxing-artifact
          path: buildkit\OpenMultiBoxing.exe
